{% set name = "clustering" %}
{% set version = "1.3.1" %}

package:
  name: moldyn-clustering
  version: {{ version }}

source:
  url: https://github.com/moldyn/{{ name }}/archive/V{{ version }}.tar.gz
  sha256: a77b4ce89b312f8ab981c1bb08a3893b3f0169e09641580364087584556eee3f

build:
  number: 2
  skip: true  # [win or osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make

  host:
    - libboost-devel

  run:

test:
  commands:
    - clustering -h 2>&1 | grep -q "a classification framework for MD data"
    - clustering density -h
    - clustering network -h

about:
  home: https://github.com/moldyn/Clustering
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Robust and stable clustering of molecular dynamics simulation trajectories

  description: |
    This software package provides extensive tools for fast, robust and 
    stable clustering of molecular dynamics trajectories. The essential 
    functions are density-based geometric clustering for microstate generation, 
    dynamic clustering based on the Most-Probable-Path algorithm (MPP),
    variable dynamic coring for boundary corrections, and dynamic noise 
    assignment. Additionally, the package includes tools to efficiently 
    filter original coordinates or order parameters based on a discrete 
    state definition to identify representative structures and variables of 
    clusters.
  dev_url: https://github.com/moldyn/Clustering

extra:
  recipe-maintainers:
    - braniii
    - simonbray
