{% set name = "clustering" %}
{% set version = "1.3.0" %}

package:
  name: moldyn-clustering
  version: {{ version }}

source:
  url: https://github.com/moldyn/{{ name }}/archive/V{{ version }}.tar.gz
  sha256: 50521a032c441362deefe2f56bf559bf1be87763a785d3805d17e1bb34056f20

build:
  number: 1
  skip: true  # [win or osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake

  host:
    - boost-cpp

  run:
    - boost-cpp

test:
  commands:
    - clustering -h 2>&1 | grep -q "a classification framework for MD data"
    - clustering density -h
    - clustering network -h

about:
  home: https://github.com/moldyn/Clustering
  license: BSD-2
  license_family: BSD
  license_file: LICENSE.txt
  summary: Robust and stable clustering of molecular dynamics simulation trajectories

  description: |
    This software package provides extensive tools for fast, robust and 
    stable clustering of molecular dynamics trajectories. The essential 
    functions are density-based geometric clustering for microstate generation, 
    dynamic clustering based on the Most-Probable-Path algorithm (MPP),
    variable dynamic coring for boundary corrections, and dynamic noise 
    assignment. Additionally, the package includes tools to efficiently 
    filter original coordinates or order parameters based on a discrete 
    state definition to identify representative structures and variables of 
    clusters.
  dev_url: https://github.com/moldyn/Clustering

extra:
  recipe-maintainers:
    - simonbray
